# - Run the transform
# - Produce RDF? (use kgx)
# - [Not Yet] QC/Validation (ex. 0 rows)
# - Create release, upload output files as release artifacts

name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install --no-interaction

      - name: Run Transform
        run: poetry run ingest transform

      